### ISSUE TITLE
Secrets are removed with ecs deploy

### ISSUE THREAD

**Issue by smuryginim** [fabfuel/ecs-deploy#93]
Hello! Thanks again for the great tool
I use version 1.7.0 and I have the next problem. 

    ecs deploy $cluster_name $APP_NAME -t $version --no-deregister --timeout -1

During the execution of the command no secrets information is copied from previous container definition to the new one
Wish you a good day!

**Comment by smuryginim** [comment]
It is interesting that problem is not reproduced on one account with the same ecs version.
Can it depend on some additional settings for aws account?
Is it possible to run in some --debug mode to check why secrets aren't copied?

**Comment by fabfuel** [comment]
Hi @smuryginim,

did you see this mention in the docs? Could it be related to the agent version of your host?
> This option was introduced by AWS in ECS Agent v1.22.0. Make sure your ECS agent version is >= 1.22.0 or else your task will not deploy.

(https://github.com/fabfuel/ecs-deploy#set-a-secret-environment-variable-from-the-aws-parameter-store)

Best
Fabian

**Comment by smuryginim** [comment]
Hello 

> Hi @smuryginim,
> 
> did you see this mention in the docs? Could it be related to the agent version of your host?
> 
> > This option was introduced by AWS in ECS Agent v1.22.0. Make sure your ECS agent version is >= 1.22.0 or else your task will not deploy.
> 
> (https://github.com/fabfuel/ecs-deploy#set-a-secret-environment-variable-from-the-aws-parameter-store)
> 
> Best
> Fabian

Hello @fabfuel. Hope you doing well!
I use Fargate service and task definition.

**Comment by smuryginim** [comment]
Similar issue with parallel tool
https://github.com/silinternational/ecs-deploy/pull/179
https://github.com/silinternational/ecs-deploy/pull/179

Maybe it is the case for you tool also?

**Comment by fabfuel** [comment]
Hi @smuryginim, 
it seems to be related to an too old version of botocore or boto3. I'll look into this.

Can you still reproduce this? Would you please share, which botocore/boto3 version you are using on the machines that work or do not work via `aws --version`?

As a quick fix, this could be a fixing work around:
```
pip install boto3 --upgrade
```

Best
Fabian

**Comment by smuryginim** [comment]
> pip install boto3 --upgrade

After executing this one command, now ecs secrets are copied! Thanks

I previously did update only aws client. That strange, because before and after update of boto3 
aws --version command provides the same output, so I was confused

before & after

```
aws --version
aws-cli/1.16.146 Python/3.6.5 Darwin/18.0.0 botocore/1.12.136
```

result of run pip install boto3 --upgrade
```
Installing collected packages: botocore, s3transfer, boto3
  Found existing installation: botocore 1.10.82
    Uninstalling botocore-1.10.82:
      Successfully uninstalled botocore-1.10.82
  Found existing installation: s3transfer 0.1.13
    Uninstalling s3transfer-0.1.13:
      Successfully uninstalled s3transfer-0.1.13
  Found existing installation: boto3 1.7.82
    Uninstalling boto3-1.7.82:
      Successfully uninstalled boto3-1.7.82
Successfully installed boto3-1.9.138 botocore-1.12.138 s3transfer-0.2.0
```

Possibly pip using its own dependencies, and aws its own. Now finally all is in sync, so problem is resolved, thanks a lot!

**Comment by IVBakker** [comment]
Best to close so that it doesn't look like the issue is still happening?
